name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  SERVICE_NAME: orderservice
  
  DOCKER_REGISTRY: registry
  DOCKER_IMAGE: docker-image
  JAVA_VERSION: '17'
  REGISTRY: tamtran0210

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'  

      - name: Build maven 
        id: maven-build
        run: |
          cd OrderService
          mvn clean install -B -DskipTests > my_Log_Build.txt 2>&1
          tail -n 10 my_Log_Build.txt
        
      - name: Check Maven Build Status
        if: ${{ steps.maven-build.outcome != 'success' }}  # Kiểm tra nếu Maven thất bại
        run: |
          echo "Maven build failed. Please check the logs above for details."
          exit 1  # Dừng pipeline nếu Maven lỗi

      - name: Set Version 
        run: |
          echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
       
      - name: Build Docker image 
        if: ${{ steps.maven-build.outcome == 'success' }}
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} .

      - name: Push Docker image to Docker Hub
        run: | 
          docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
