name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  SERVICE_NAME: OrderService
  DOCKER_REGISTRY: registry
  DOCKER_IMAGE: docker-image
  JAVA_VERSION: '17'
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username:${{secrets.DOCKER_USERNAME}}
        password:${{secrets.DOCKER_PASSWD}}
       
    - name:


       
 
    
        
      
